### ISSUE TITLE
Threading model

### ISSUE THREAD

**Issue by flip111** [jreese/aiosqlite#2]
I'm a little confused by the wording in the readme. Does this ` It does this by using a single, shared thread per connection.` mean there is a single thread shared between all connections or there is one thread per connection (but how is it then shared ?). How many threads are started ?

Is this library in any way related to [Write-Ahead Logging](https://sqlite.org/wal.html)?

**Comment by p4l1ly** [comment]
By reading the code, I think it is one thread per connection. The thing is that if you try to use sqlite3 library and just ran the calls in asyncio.get_event_loop().run_in_executor, you encounter soon a problem. Event loop executor spawns a new thread for every call to run_in_executor. Sqlite complains because all the operations with a connection must be run in the same thread. You can run all the sqlite operations in one big run_in_executor call. But it has disadvantages - e. g. you cannot cancel the big procedure in the middle. This library solves the problem - it runs all the operations in a single thread.

**Comment by jreese** [comment]
This library is shared-thread-per-connection.  If you start a new connection for every query, then you'll end up with as many threads as you have simultaneous queries, but you won't block the main asyncio event loop in the process.  If you share a single connection object for all queries, then there will only be one shared thread, and all queries will be executed in a queued fashion.  As @p4l1ly mentions, this design is due to a lack of thread safety in the standard sqlite3 connection mechanism.

Also, this is unrelated to WAL.  It's just a simple mirror of the standard sqlite3 API to support asyncio.  You can activate WAL by sending the appropriate PRAGMA query the same as you would with the standard module.
