### ISSUE TITLE
Long lived connection

### ISSUE THREAD

**Issue by krishna-kashyap** [jreese/aiosqlite#7]
Hi,

This isn't as much of a bug, so doing away with the template, apologies for that

I was trying to use aiosqlite with a simple web server app and would have liked to use something like a app wide connection or a pool of connections. However couldn't find much on how to get this done. Digging into the code saw context manager was used to control the thread.

Couple of questions to help me understand and use the lib better

1. Is it unsafe for multiple coroutines (async defs) to be using a single sqlite DB connection thread? Anything found while developing leading to make the design decision?
2. If no, would it be possible to have code in the Connection class to provide long living connection? (If yes I'd be willing to work on a PR)

If I missed something which could be used for the above use case, please help me understand it better

**Comment by jreese** [comment]
Safety-wise, it should be fine to use a shared connection (there are unit tests for this behavior), as long as they don't share cursors, but it will be slower than separate connections, since each connection can only execute a single query or cursor method at once, even if it's blocking on I/O.  For sharing a connection, either wrap the entry point in a function that uses the context manager and passes the connection through, or `await db.__aenter__()` and `await db.__aexit__()` directly at start/stop. 

A connection pool would be a nice option to have, and shouldn't be too difficult to implement and round-robin across connections, but also note that simultaneous connections will generally lock the entire database for writes, so any need for high concurrency would probably be best served by using something other than Sqlite entirely.

**Comment by krishna-kashyap** [comment]
Thanks for the prompt response. I implemented the former approach wrapping the __aenter__. Let me know if it would help to provide a public method to do the same and use that inside __aeneter__ instead.
